---
ID: "4796a6e6-6c4f-5247-b3d2-09385e5fe8e0"
Parent: "8f5de718-d14f-54fb-a5de-b4cafa1b96bd"
Template: "8f5de718-d14f-54fb-a5de-b4cafa1b96bd"
Path: "/sitecore/templates/Project/lighthousefitness-kiosk/lookup/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181227T054321Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
