---
ID: "852c8264-ee81-5a60-916a-7533c4c2d4cd"
Parent: "36916497-e872-5b5d-9464-a6264ce78c61"
Template: "36916497-e872-5b5d-9464-a6264ce78c61"
Path: /sitecore/templates/Project/habitatfitness/SaveAsAccountStep/__Standard Values
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181027T230930Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
