---
ID: "badf4c00-6c11-5573-a89d-0687d2710a99"
Parent: "ce103ece-138c-5434-ad89-5adbc3bd952e"
Template: "ce103ece-138c-5434-ad89-5adbc3bd952e"
Path: /sitecore/templates/Project/habitatfitness/EventDetailLoggedIn/__Standard Values
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181027T230928Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8e1d428f-9fd3-4076-b40d-8445ab7bd60d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190820T161722Z
