---
ID: "a6937ddd-506d-51e5-bd6e-da4ffb072ad0"
Parent: "8e2721fe-f0e9-545e-a2d6-d2a9e0d9bd1d"
Template: "8e2721fe-f0e9-545e-a2d6-d2a9e0d9bd1d"
Path: "/sitecore/templates/Project/lighthousefitness-kiosk/ChangeLocation/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181227T054322Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
