---
ID: "949236f3-ecca-5847-9b87-b92589a6f54c"
Parent: "551c1312-27ac-5a3b-9a6b-62db47ed571c"
Template: "551c1312-27ac-5a3b-9a6b-62db47ed571c"
Path: /sitecore/templates/Project/habitatfitness/Profile Key/__Standard Values
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181024T200341Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
