---
ID: "05ce9dc9-85dd-5bc5-8e63-31f3e9a6d69c"
Parent: "80f32942-afab-59c0-91f8-af33cbf166f9"
Template: "80f32942-afab-59c0-91f8-af33cbf166f9"
Path: "/sitecore/templates/Project/habitatfitness/event-label/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181024T200340Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "741cd00c-93ab-5967-89a7-d2916c98c246"
      Hint: name
      Value: $name
