---
ID: "0d788bb4-2211-578b-b2c9-46f33476259f"
Parent: "0fdb64bb-3e2e-5b87-ad2b-b7a49a06864e"
Template: "0fdb64bb-3e2e-5b87-ad2b-b7a49a06864e"
Path: /sitecore/templates/Project/habitatfitness/Login/__Standard Values
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181024T200342Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
