---
ID: "da161b64-bf47-59cb-91c7-d97fa1500ac5"
Parent: "3bfbb1a1-5cbe-5e04-b131-2175be256de1"
Template: "3bfbb1a1-5cbe-5e04-b131-2175be256de1"
Path: "/sitecore/templates/Project/habitatfitness/wizard-step-component/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181027T230928Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
