---
ID: "f8843bf7-a31a-4f71-8900-abd56b8fe34c"
Parent: "bbf6ffcd-cb4b-4363-a715-b2706e1b8ff9"
Template: "8ce42210-cad0-44f8-8ada-d88834a7ed2e"
Path: /sitecore/system/Modules/CMP/Config
DB: master
SharedFields:
- ID: "0b8e14d1-6a2d-46b9-b2e8-f51c32c0d0e8"
  Hint: Content Hub URI
  Value: "https://scmdemoinstance.stylelabs.io/en-us"
- ID: "0fe08d15-b948-4375-9a88-4a8fb2cb980e"
  Hint: Connection String
  Value: "Endpoint=sb://sitecorecmpdemo.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=U2PvyzBPuc0fo4bd+0JCUpmE36I4SJz5v2xAPSTKIM4="
- ID: "21ca0142-2d9e-46ce-99e6-12adeebcd635"
  Hint: Default Language
  Value: en
- ID: "3d857aa4-8e43-41df-bfda-f83368555cb2"
  Hint: Incoming topic name
  Value: m_out
- ID: "4f34ff99-f829-4c6c-92a6-a85975acb7dc"
  Hint: User Name
  Value: sitecoreuser
- ID: "51c956b7-6f65-4605-9476-4441f0904495"
  Hint: Outgoing topic name
  Value: m_in
- ID: "5a891676-3468-4575-8d97-0e4b2bdc3e78"
  Hint: Password
  Value: "Sitecore12!@#$%^&*()"
- ID: "71aa4d06-34f7-49ab-93db-acb0a53ea544"
  Hint: Client Id
  Value: LogicApp
- ID: "e0bea0ba-0f96-49ef-b73c-1f743b608f87"
  Hint: Incoming subscription name
  Value: sitecore
- ID: "e6c706e7-8f4b-4f43-b29b-a22d1bacd59e"
  Hint: Client Secret
  Value: "d54a8fb6-45f7-4404-a930-4bfc05ce6cb5"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190205T134908Z
