---
ID: "10d1c6cc-358c-538b-be5d-d8c1c9d2408f"
Parent: "22b98804-a2d5-5233-9245-640892d0e598"
Template: "22b98804-a2d5-5233-9245-640892d0e598"
Path: /sitecore/templates/Project/lighthousefitness/MyEvents/__Standard Values
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181231T024859Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
