---
ID: "4a9c48e3-1534-56de-857a-eb04b4531508"
Parent: "a6affa37-6e8a-588e-b6ef-955c4b47a47d"
Template: "a6affa37-6e8a-588e-b6ef-955c4b47a47d"
Path: "/sitecore/templates/Project/lighthousefitness-kiosk/KioskEventList/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181227T054323Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
