---
ID: "dfad68dc-c75a-5018-a547-fd5f3526a794"
Parent: "40a63e80-390d-5c17-869f-7eb9b5bfd2d7"
Template: "40a63e80-390d-5c17-869f-7eb9b5bfd2d7"
Path: /sitecore/templates/Project/habitatfitness/SelectFormField/__Standard Values
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181024T200343Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
