---
ID: "36758f1c-8212-547d-ab19-dc9e6a3301a9"
Parent: "92c6b0a9-42ee-5884-bc16-057318857540"
Template: "92c6b0a9-42ee-5884-bc16-057318857540"
Path: /sitecore/templates/Project/habitatfitness/SportsPickerStep/__Standard Values
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181027T230930Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
